export const POPULAR_FOR_OPTIONS = [
  "Weddings",
  "Corporate",
  "Baby Showers",
  "Photoshoots",
  "Birthdays",
  "Bridal Showers",
  "Graduations",
  "Holiday Parties",
  "Concert",
  "Proposal",
  "Bachelor Party",
  "Bachelorette Party",
  "Anniversary",
  "Gender Reveal",
  "Quinceañera",
  "Baptism",
  "Funeral",
  "Reunion",
  "Conference",
  "Sporting",
  "School Dance",
  "Other",
] as const;

export const EVENT_TYPE_OPTIONS = [
  { value: "wedding", label: "Wedding" },
  { value: "corporate", label: "Corporate Event" },
  { value: "baby-shower", label: "Baby Shower" },
  { value: "photoshoot", label: "Photoshoot" },
  { value: "birthday", label: "Birthday" },
  { value: "bridal-shower", label: "Bridal Shower" },
  { value: "graduation", label: "Graduation" },
  { value: "holiday-party", label: "Holiday Party" },
  { value: "concert", label: "Concert" },
  { value: "proposal", label: "Proposal" },
  { value: "bachelor-party", label: "Bachelor Party" },
  { value: "bachelorette-party", label: "Bachelorette Party" },
  { value: "anniversary", label: "Anniversary" },
  { value: "gender-reveal", label: "Gender Reveal" },
  { value: "quinceanera", label: "Quinceañera" },
  { value: "baptism", label: "Baptism" },
  { value: "funeral", label: "Funeral" },
  { value: "reunion", label: "Reunion" },
  { value: "conference", label: "Conference" },
  { value: "sporting", label: "Sporting" },
  { value: "school-dance", label: "School Dance" },
  { value: "gala", label: "Gala" },
  { value: "other", label: "Other" },
] as const;
